```cpp
// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! modified//
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// rgb //
// --- //

#define rgb_wrap_target 2
#define rgb_wrap 9

static const uint16_t rgb_program_instructions[] = {
    0x80a0, //  0: pull   block                      
    0xa047, //  1: mov    y, osr                     
            //     .wrap_target
    0xe000, //  2: set    pins, 0                    
    0xa022, //  3: mov    x, y                       
    0x23c1, //  4: wait   1 irq, 1               [3] 
    0x80a0, //  5: pull   block                      
    0x6405, //  6: out    pins, 5                [4] 
    0x6205, //  7: out    pins, 5                [2] 
    0x6005, //  8: out    pins, 5                    
    0x0045, //  9: jmp    x--, 5                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rgb_program = {
    .instructions = rgb_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config rgb_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rgb_wrap_target, offset + rgb_wrap);
    return c;
}

static inline void rgb_program_init(PIO pio, uint sm, uint offset, uint pin_red) {
    pio_sm_config c = rgb_program_get_default_config(offset);
    // Configure SET pins (used for "set pins, 0" blanking)
    // We'll use GPIO 0 as the base for the 15-pin range
    sm_config_set_set_pins(&c, 0, 15);
    // Configure OUT pins to output 5-bit values
    // First OUT instruction outputs bits [15:11] (RED) to GPIO 0-4
    sm_config_set_out_pins(&c, 0, 15);
    // Initialize all 15 GPIO pins for output
    for (int i = 0; i < 5; i++) {
        pio_gpio_init(pio, i);              // RED: GPIO 0-4
    }
    for (int i = 6; i < 11; i++) {
        pio_gpio_init(pio, i);              // GREEN: GPIO 6-10
    }
    for (int i = 11; i < 16; i++) {
        pio_gpio_init(pio, i);              // BLUE: GPIO 11-15
    }
    // Set pin direction to output for all 15 pins
    for (int i = 0; i < 5; i++) {
        pio_sm_set_consecutive_pindirs(pio, sm, i, 1, true);
    }
    for (int i = 6; i < 11; i++) {
        pio_sm_set_consecutive_pindirs(pio, sm, i, 1, true);
    }
    for (int i = 11; i < 16; i++) {
        pio_sm_set_consecutive_pindirs(pio, sm, i, 1, true);
    }
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
}

#endif

```